package io.quarkiverse.langfuse.it.otel;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import java.net.URL;
import java.time.Duration;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import jakarta.inject.Inject;
import jakarta.ws.rs.core.Response.Status;

import org.junit.jupiter.api.Test;

import com.langfuse.api.LangfuseApi;
import com.langfuse.api.legacyObservationsV1.LegacyObservationsV1Api.APILegacyObservationsV1GetManyRequest;
import com.langfuse.api.model.LegacyObservationsViews;
import com.langfuse.api.model.ObservationsView;
import com.langfuse.api.model.TraceWithDetails;
import com.langfuse.api.model.Traces;
import com.langfuse.api.trace.TraceApi.APITraceListRequest;

import io.quarkiverse.langfuse.rest.ChatResource;
import io.quarkus.test.common.http.TestHTTPEndpoint;
import io.quarkus.test.common.http.TestHTTPResource;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.http.ContentType;

@QuarkusTest
public class LangfuseOtelTests {
    @Inject
    LangfuseApi langfuseApi;

    @TestHTTPEndpoint(ChatResource.class)
    @TestHTTPResource
    URL chatResourceUrl;

    @Test
    void otelTracesPropagatedToLangfuse() throws InterruptedException {
        // There may already be traces in Langfuse from other tests
        // So we need to make sure that this test only checks traces generated by this test
        // by getting the existing trace IDs before

        TimeUnit.SECONDS.sleep(5); // Gives time for any previous traces to be exported

        var beginningTraceIds = getTraces().stream()
                .map(TraceWithDetails::getId)
                .collect(Collectors.toSet());

        var response = given()
                .queryParam("message", "Help me!")
                .get(this.chatResourceUrl)
                .then()
                .statusCode(Status.OK.getStatusCode())
                .contentType(ContentType.TEXT)
                .extract().asString();

        assertThat(response)
                .isNotBlank();

        await()
                .atMost(Duration.ofSeconds(20))
                .pollInterval(Duration.ofSeconds(1))
                .pollDelay(Duration.ofSeconds(5)) // Gives time for the traces to be exported
                .untilAsserted(() -> assertThat(getTraces())
                        .hasSizeGreaterThan(beginningTraceIds.size())
                        .anySatisfy(trace -> assertTraceHasAtLeastOneGenAIObservation(trace, beginningTraceIds)));
    }

    private void assertTraceHasAtLeastOneGenAIObservation(TraceWithDetails trace, Set<String> beginningTraceIds) {
        assertThat(beginningTraceIds).doesNotContain(trace.getId());
        assertThat(getObservations(trace.getId()))
                .isNotEmpty()
                .anySatisfy(observation -> {
                    assertThat(observation.getType()).isEqualToIgnoringCase("GENERATION");
                    assertThat(observation.getInput()).isNotNull();
                });
    }

    private List<ObservationsView> getObservations(String traceId) {
        var request = APILegacyObservationsV1GetManyRequest.newBuilder()
                .traceId(traceId)
                .build();

        return Optional.ofNullable(this.langfuseApi.legacyObservationsV1().legacyObservationsV1GetMany(request))
                .map(LegacyObservationsViews::getData)
                .orElseGet(List::of);
    }

    private List<TraceWithDetails> getTraces() {
        return Optional.ofNullable(this.langfuseApi.trace().traceList(APITraceListRequest.newBuilder().build()))
                .map(Traces::getData)
                .orElseGet(List::of);
    }
}
