open module com.langfuse.api {
    requires static org.jspecify;
    requires static jakarta.annotation;
    requires static jakarta.validation;
    requires static com.fasterxml.jackson.annotation;
    requires static com.fasterxml.jackson.core;
    requires static com.fasterxml.jackson.databind;
    requires static tools.jackson.core;
    requires static tools.jackson.databind;
    requires java.logging;

    exports com.langfuse.api;
    exports com.langfuse.api.spi;
    exports com.langfuse.api.model;
    exports com.langfuse.api.annotationQueues;
    exports com.langfuse.api.annotationQueues.async;
    exports com.langfuse.api.blobStorageIntegrations;
    exports com.langfuse.api.blobStorageIntegrations.async;
    exports com.langfuse.api.comments;
    exports com.langfuse.api.comments.async;
    exports com.langfuse.api.datasetItems;
    exports com.langfuse.api.datasetItems.async;
    exports com.langfuse.api.datasetRunItems;
    exports com.langfuse.api.datasetRunItems.async;
    exports com.langfuse.api.datasets;
    exports com.langfuse.api.datasets.async;
    exports com.langfuse.api.health;
    exports com.langfuse.api.health.async;
    exports com.langfuse.api.ingestion;
    exports com.langfuse.api.ingestion.async;
    exports com.langfuse.api.legacyMetricsV1;
    exports com.langfuse.api.legacyMetricsV1.async;
    exports com.langfuse.api.legacyObservationsV1;
    exports com.langfuse.api.legacyObservationsV1.async;
    exports com.langfuse.api.legacyScoreV1;
    exports com.langfuse.api.legacyScoreV1.async;
    exports com.langfuse.api.llmConnections;
    exports com.langfuse.api.llmConnections.async;
    exports com.langfuse.api.media;
    exports com.langfuse.api.media.async;
    exports com.langfuse.api.metrics;
    exports com.langfuse.api.metrics.async;
    exports com.langfuse.api.models;
    exports com.langfuse.api.models.async;
    exports com.langfuse.api.observations;
    exports com.langfuse.api.observations.async;
    exports com.langfuse.api.opentelemetry;
    exports com.langfuse.api.opentelemetry.async;
    exports com.langfuse.api.organizations;
    exports com.langfuse.api.organizations.async;
    exports com.langfuse.api.projects;
    exports com.langfuse.api.projects.async;
    exports com.langfuse.api.promptVersion;
    exports com.langfuse.api.promptVersion.async;
    exports com.langfuse.api.prompts;
    exports com.langfuse.api.prompts.async;
    exports com.langfuse.api.scim;
    exports com.langfuse.api.scim.async;
    exports com.langfuse.api.scoreConfigs;
    exports com.langfuse.api.scoreConfigs.async;
    exports com.langfuse.api.scores;
    exports com.langfuse.api.scores.async;
    exports com.langfuse.api.sessions;
    exports com.langfuse.api.sessions.async;
    exports com.langfuse.api.trace;
    exports com.langfuse.api.trace.async;
    exports com.langfuse.api.unstableEvaluationRules;
    exports com.langfuse.api.unstableEvaluationRules.async;
    exports com.langfuse.api.unstableEvaluators;
    exports com.langfuse.api.unstableEvaluators.async;

    uses com.langfuse.api.spi.LangfuseApiBuilderFactory;
}
