quarkus.openapi-generator.langfuse_yml.auth.basic_auth.username=${quarkus.langfuse.username}
quarkus.openapi-generator.langfuse_yml.auth.basic_auth.password=${quarkus.langfuse.password}
quarkus.openapi-generator.codegen.include=langfuse.yml
quarkus.openapi-generator.codegen.initialize-empty-collections=true
quarkus.openapi-generator.codegen.use-bean-validation=true
quarkus.openapi-generator.codegen.type-mappings.DateTime=Instant
quarkus.openapi-generator.codegen.import-mappings.Instant=java.time.Instant
quarkus.openapi-generator.codegen.schema-mappings.EvaluationRuleFilter=io.quarkiverse.langfuse.client.model.EvaluationRuleFilter
quarkus.openapi-generator.codegen.schema-mappings.CreateScoreValue=io.quarkiverse.langfuse.client.model.CreateScoreValue
quarkus.openapi-generator.codegen.open-api-normalizer.SIMPLIFY_ONEOF_ANYOF=true
quarkus.openapi-generator.codegen.spec.langfuse_yml.config-key=langfuse-api
quarkus.openapi-generator.codegen.spec.langfuse-api.base-package=io.quarkiverse.langfuse.client
quarkus.openapi-generator.codegen.spec.langfuse-api.config-key=langfuse
quarkus.openapi-generator.codegen.spec.langfuse-api.use-dynamic-url=false
quarkus.openapi-generator.codegen.spec.langfuse-api.register-rest-client=false
quarkus.openapi-generator.codegen.spec.langfuse-api.api-cdi-scope=none
quarkus.openapi-generator.codegen.spec.langfuse-api.method-per-media-type=true
quarkus.openapi-generator.codegen.spec.langfuse-api.generate-model-for-usage-as-bean-param=true