quarkus.http.test-port=0

quarkus.log.category."io.quarkiverse.langfuse".level=DEBUG

quarkus.langfuse.log-requests=true
quarkus.langfuse.log-responses=true
quarkus.langfuse.pretty-print=true

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.openai.api-key=change-me

%dev,test.quarkus.langchain4j.openai.base-url=http://localhost:${quarkus.wiremock.devservices.port}/v1/

%dev,test.quarkus.wiremock.devservices.files-mapping=src/test/resources/wiremock